name: Build Chromium

on: push

jobs:
  build-chromium:
    name: Build Chromium
    runs-on: ubuntu-16.04

    steps:
      - name: Install build dependencies
        run: apt-get --just-print install -f libasound2:i386 libcap2:i386 libelf-dev:i386 libfontconfig1:i386 libglib2.0-0:i386 libgpm2:i386 libncurses5:i386 libnss3:i386 libpango-1.0-0:i386 libpci3:i386 libssl1.1:i386 libssl-dev:i386 libtinfo-dev:i386 libudev1:i386 libuuid1:i386 libx11-xcb1:i386 libxcomposite1:i386 libxcursor1:i386 libxdamage1:i386 libxi6:i386 libxrandr2:i386 libxss1:i386 libxtst6:i386 linux-libc-dev:i386 ant apache2-bin autoconf binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabihf binutils-mips64el-linux-gnuabi64 binutils-mipsel-linux-gnu bison bzip2 cdbs cmake curl dbus-x11 devscripts dpkg-dev elfutils fakeroot flex g++-5-multilib g++-5-multilib-arm-linux-gnueabihf g++-arm-linux-gnueabihf gawk gcc-5-multilib-arm-linux-gnueabihf gcc-arm-linux-gnueabihf git-core g++-mingw-w64-i686 gperf intltool lib32gcc1 lib32ncurses5-dev lib32stdc++6 lib32z1-dev libapache2-mod-php7.4 libappindicator3-1 libappindicator3-dev libasound2 libasound2-dev libatk1.0-0 libatspi2.0-0 libatspi2.0-dev libav-tools libbluetooth-dev libbrlapi0.6 libbrlapi-dev libbz2-1.0 libbz2-dev libc6 libc6-dev libc6-dev-armhf-cross libc6-i386 libcairo2 libcairo2-dev libcap2 libcap-dev libcups2 libcups2-dev libcurl4-gnutls-dev libdrm2 libdrm-dev libelf-dev libevdev2 libevdev-dev libexpat1 libffi6 libffi-dev libfontconfig1 libfreetype6 libgbm1 libgbm-dev libglib2.0-0 libglib2.0-dev libglu1-mesa-dev libgnome-keyring0 libgnome-keyring-dev libgtk-3-0 libgtk-3-dev libinput10 libinput-dev libjpeg-dev libkrb5-dev libnspr4 libnspr4-dev libnss3 libnss3-dev libpam0g libpam0g-dev libpango-1.0-0 libpci3 libpci-dev libpcre3 libpixman-1-0 libpng16-16 libpulse0 libpulse-dev libsctp-dev libspeechd2 libspeechd-dev libsqlite3-0 libsqlite3-dev libssl-dev libstdc++6 libtinfo5 libtinfo-dev libtool libudev1 libudev-dev libuuid1 libvulkan1 libvulkan-dev libwayland-egl1-mesa libwww-perl libx11-6 libx11-xcb1 libxau6 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 libxinerama1 libxkbcommon-dev libxrandr2 libxrender1 libxslt1-dev libxss-dev libxt-dev libxtst6 libxtst-dev linux-libc-dev-armhf-cross locales openbox p7zip patch perl php7.4-cgi pkg-config python python-crypto python-dev python-numpy python-openssl python-psutil python-setuptools python-yaml realpath rpm ruby snapcraft subversion texinfo uuid-dev wdiff x11-utils xcompmgr xsltproc xutils-dev xvfb xz-utils zip zlib1g
      - name: Clone depot_tools repository
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "${PWD}/depot_tools" >> $GITHUB_PATH
      - name: Fetch chromium repository
        run: |
          mkdir chromium
          cd chromium
          fetch --no-history --nohooks chromium
      - name: Install build dependencies
        working-directory: chromium/src
        run: |
          ./build/install-build-deps.sh
          ./build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
          gclient runhooks
      - name: Patch out assertions
        working-directory: chromium/src
        run: |
          sed -i.bak 's/assert(current_toolchain == default_toolchain)/# assert(current_toolchain == default_toolchain)/' ./build/config/linux/atk/BUILD.gn
          sed -i.bak 's/assert(current_toolchain == default_toolchain)/# assert(current_toolchain == default_toolchain)/' ./build/config/linux/atspi2/BUILD.gn
      - name: Create build directory and configure cross-compilation
        working-directory: chromium/src
        run: gn gen out/Default --args='target_os="linux" target_cpu="arm64" is_debug=false symbol_level=0 enable_nacl=false blink_symbol_level=0'
      - name: Compile chromium
        working-directory: chromium/src
        run: autoninja -C out/Default chrome
      - name: Create rpm installer
        working-directory: chromium/src
        run: autoninja -C out/Default chrome/installer/linux:stable_rpm
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-rpm
          path: chromium/src/out/Default/chromium-browser-stable-*.rpm
